language: java
script: cd bundles/fr.univnantes.alma.releng && mvn clean verify
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: Tbr20mUbCh6xYYgDHcZJ6ManQiZNw6viMUg8cKMeK9YkkdnwAaZIz2whgdpWJR+mCjbB4n3QcFzNqbxQFeybVnD7Kb4qNAkaee6inNXh+SzEZz8nBPgANV85Ghwt/PFJec4Vp0/wQ5M9/z93MCY+lo+l0b9FL0jw7zTuMk90P6F2c5jgrluZShuevdoZoSM7rXTOZr7bzmDWZvM0VBgx/HlIm1slHMinPKZ3tOAnOtIMW2AN0FhW+JSUCGb+22bDy3SvMW6azxQ87MjxaFX3HCEP7qZY7yxw7/ctPp5uf5/RdmjrV/NyoPpexJEh3KJ2Sx/9S91N/6HHVCocHX3D3nW3nr8rzfhfbCgaJOwU0hDGP1CTk+WNVeCpnCPf8v5SX+6DINrnxHIQyO91PtaErsfK54EJGnl6idvqZwX+LUvcOXEfOAzzaKzwxPEygSB/UhJZ4MB+gYnsGY7iXt5zDV5MGkCARh/NPYbQBf2Mi/4TSqAufWJzaiLvgJCrttgXgvmHtGlty3N95qp598+OHpd7qu9sy4zMSK3rSQa8UoBa4B9vlIqjI01jMZJD7/VkFDx5j9amXZTk+N2dqn5yhIkUrpHuzPI3/A+w+6jHrVXjxS5jaFr4Ry3xtMlgz3aH7C9Gzjzm5ERxLnEezYvxrh9kzhjZcQT+apKH+7iXdn4=
  file:
    - "../fr.univnantes.alma.repository/target/products/ALMAServer-linux.gtk.x86_64.zip"
    - "../fr.univnantes.alma.repository/target/products/ALMAServer-macosx.cocoa.x86_64.zip"
    - "../fr.univnantes.alma.repository/target/products/ALMAServer-win32.win32.x86_64.zip"
  skip_cleanup: true
  on:
    tags: true

