language: java
script: cd bundles/fr.univnantes.alma.releng && mvn clean verify
jdk: oraclejdk8
deploy:
  provider: releases
  api-key: f4c56bf99ddb6749b9ca69682fbd4b902de1348d
  file:
    - "bundles/fr.univnantes.alma.repository/target/products/ALMAServer-linux.gtk.x86_64.zip"
    - "bundles/fr.univnantes.alma.repository/target/products/ALMAServer-macosx.cocoa.x86_64.zip"
    - "bundles/fr.univnantes.alma.repository/target/products/ALMAServer-win32.win32.x86_64.zip"
  skip_cleanup: true
  on:
    tags: true

