language: java
script: cd bundles/fr.univnantes.alma.releng && mvn clean verify
jdk: oraclejdk8
deploy:
  provider: releases
  api_key: f1abdf1a84f981cc8cdad9072be6389bade0f808
  file:
    - "bundles/fr.univnantes.alma.repository/target/products/ALMAServer-linux.gtk.x86_64.zip"
    - "bundles/fr.univnantes.alma.repository/target/products/ALMAServer-macosx.cocoa.x86_64.zip"
    - "bundles/fr.univnantes.alma.repository/target/products/ALMAServer-win32.win32.x86_64.zip"
  skip_cleanup: true
  on:
    tags: true

